export const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Lcov reporter" />
    <link rel="shortcut icon" href="{{ favicon }}" type="image/x-icon">
    <title>{{ projectTitle }}</title>
    <script>{{ themeInit }}</script>
    <style>{{ mainCss }}</style>
    <style>{{ indexCss }}</style>
  </head>
  <body>
    <main>
      <div class="banner">
       <h1>{{ projectName }}</h1>
       <div class="banner-controls">
          {{ bannerNav }}
           <button
            type="button"
            id="theme-btn"
            aria-label="Theme switch button"
          ></button>
        </div>
        <div class="report">
          <div class="item">
            <div class="label">Total Lines Coverage</div>
            <div class="result {{ totalLinesClass }}">
              <p>
                <span class="percent">{{ totalLinesPercentage }}</span>
                <span class="info">{{ totalLinesInfo }}</span>
              </p>
            </div>
          </div>
          <div class="item">
            <div class="label">Total Functions Coverage</div>
            <div class="result {{ totalFunctionsClass }}">
              <p>
                <span class="percent">{{ totalFunctionsPercentage }}</span>
                <span class="info">{{ totalFunctionsInfo }}</span>
              </p>
            </div>
          </div>
          <div class="item">
            <div class="label">Total Branches Coverage</div>
            <div class="result {{ totalBranchesClass }}">
              <p>
                <span class="percent">{{ totalBranchesPercentage }}</span>
                <span class="info">{{ totalBranchesInfo }}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="table-wrapper">
        <table>
          <thead>
            <tr>
              <th>File</th>
              <th>Line Coverage</th>
              <th>Lines</th>
              <th>Function Coverage</th>
              <th>Functions</th>
              <th>Branch Coverage</th>
              <th>Branches</th>
            </tr>
          </thead>
          <tbody>{{ tableRows }}</tbody>
        </table>
      </div>
      <div class="badge-container">
        <h2>Badge</h2>
        <div class="badge-code" data-shiki-highlighter>
          <div class="code-head">
            <span>Markdown</span>
            <button type="button" aria-label="Copy markdown badge" data-copy-btn></button>
          </div>
          {{ mdBadge }}
        </div>
        <div class="badge-code" data-shiki-highlighter>
          <div class="code-head">
            <span>HTML</span>
            <button type="button" aria-label="Copy HTML badge" data-copy-btn></button>
          </div>
          {{ htmlBadge }}
        </div>
      </div>
       <footer class="footer">
        <small
          ><i
            >Generated by
            <a href="https://github.com/phothinmg/mmcov" target="_blank" aria-label="Go to mmcov github repo"
              >mmcov</a
            ></i
          ></small
        >
      </footer>
    </main>
    <script>{{ themeScript }}</script>
    <script>{{ copyBtn }}</script>
  </body>
</html>
`;
