// cspell:disable
export const fileHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Lcov reporter" />
    <link rel="shortcut icon" href="{{ favicon }}" type="image/x-icon">
    <title>{{ fileTitle }}</title>
    <script>{{ themeInit }}</script>
    <style>{{ mainCss }}</style>
    <style>{{ fileCss }}</style>
  </head>
  <body>
    <main>
      <div class="banner">
       <h1>{{ fileName }}</h1>
       <div class="banner-controls">
          <a
            class="back-home"
            href="index.html"
            aria-label="Go back to all files page"
            >&larr; Back to all files</a
          >
           <button
            type="button"
            id="theme-btn"
            aria-label="Theme switch button"
          ></button>
        </div>
        <div class="report">
          <div class="item">
            <div class="label">Lines Coverage</div>
            <div class="result {{ linesClass }}">
              <p>
                <span class="percent">{{ linesPercentage }}</span>
                <span class="info">{{ linesInfo }}</span>
              </p>
            </div>
          </div>
          <div class="item">
            <div class="label">Functions Coverage</div>
            <div class="result {{ functionsClass }}">
              <p>
                <span class="percent">{{ functionsPercentage }}</span>
                <span class="info">{{ functionsInfo }}</span>
              </p>
            </div>
          </div>
          <div class="item">
            <div class="label">Branches Coverage</div>
            <div class="result {{ branchesClass }}">
              <p>
                <span class="percent">{{ branchesPercentage }}</span>
                <span class="info">{{ branchesInfo }}</span>
              </p>
            </div>
          </div>
        </div>
      </div>
      {{ shiki }}
       <footer class="footer">
        <small
          ><i
            >Generated by
            <a href="https://github.com/phothinmg/mmcov" target="_blank" aria-label="Go to mmcov github repo"
              >mmcov</a
            ></i
          ></small
        >
      </footer>
    </main>
    <script>{{ themeScript }}</script>
  </body>
</html>
`;
