export const rex = {
	// main document
	favicon: /\{\{\s*favicon\s*\}\}/gm,
	themeInit: /\{\{\s*themeInit\s*\}\}/gm,
	mainCss: /\{\{\s*mainCss\s*\}\}/gm,
	themeScript: /\{\{\s*themeScript\s*\}\}/gm,
	// file 13 items
	fileTitle: /\{\{\s*fileTitle\s*\}\}/gm,
	fileCss: /\{\{\s*fileCss\s*\}\}/gm,
	fileName: /\{\{\s*fileName\s*\}\}/gm,
	linesClass: /\{\{\s*linesClass\s*\}\}/gm,
	linesPercentage: /\{\{\s*linesPercentage\s*\}\}/gm,
	linesInfo: /\{\{\s*linesInfo\s*\}\}/gm,
	functionsClass: /\{\{\s*functionsClass\s*\}\}/gm,
	functionsPercentage: /\{\{\s*functionsPercentage\s*\}\}/gm,
	functionsInfo: /\{\{\s*functionsInfo\s*\}\}/gm,
	branchesClass: /\{\{\s*branchesClass\s*\}\}/gm,
	branchesPercentage: /\{\{\s*branchesPercentage\s*\}\}/gm,
	branchesInfo: /\{\{\s*branchesInfo\s*\}\}/gm,
	shiki: /\{\{\s*shiki\s*\}\}/gm,
	// index page
	projectName: /\{\{\s*projectName\s*\}\}/gm,
	projectTitle: /\{\{\s*projectTitle\s*\}\}/gm,
	indexCss: /\{\{\s*indexCss\s*\}\}/gm,
	totalLinesClass: /\{\{\s*totalLinesClass\s*\}\}/gm,
	totalLinesPercentage: /\{\{\s*totalLinesPercentage\s*\}\}/gm,
	totalLinesInfo: /\{\{\s*totalLinesInfo\s*\}\}/gm,
	totalFunctionsClass: /\{\{\s*totalFunctionsClass\s*\}\}/gm,
	totalFunctionsPercentage: /\{\{\s*totalFunctionsPercentage\s*\}\}/gm,
	totalFunctionsInfo: /\{\{\s*totalFunctionsInfo\s*\}\}/gm,
	totalBranchesClass: /\{\{\s*totalBranchesClass\s*\}\}/gm,
	totalBranchesPercentage: /\{\{\s*totalBranchesPercentage\s*\}\}/gm,
	totalBranchesInfo: /\{\{\s*totalBranchesInfo\s*\}\}/gm,
	tableRows: /\{\{\s*tableRows\s*\}\}/gm,
	badge: /\{\{\s*badge\s*\}\}/gm,
	mdBadge: /\{\{\s*mdBadge\s*\}\}/gm,
	htmlBadge: /\{\{\s*htmlBadge\s*\}\}/gm,
	copyBtn: /\{\{\s*copyBtn\s*\}\}/gm,
};
